language: node_js
notifications:
  email: false
node_js:
  - '10'
before_script:
  - npm prune
after_success:
  - npm run build:production
  - npm run semantic-release
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
